import colours from "../../config/colours";
const styles = {
    container: {
        flex: 1,
        backgroundColor: colours.backgroundColour,
        alignItems: 'center',
        paddingHorizontal: 25,
        gap: 18,
    },
    currentSessionView: {
        backgroundColor: colours.backgroundAccent,
        borderRadius: 11,
        padding: 9,
        width: '100%',
        alignItems: 'flex-start',
        justifyContent: 'center',
        display: 'flex',
        flexDirection: 'column',
        gap: 5,
        shadowOffset: {height: 2},
        shadowOpacity: 0.3,
        shadowRadius: 3,
        shadowColor: colours.shadowDarkColour,
        elevation: 8,
    },
    currentSessionTextContainer: {
        display: 'flex',
        width: '100%',
        flexDirection: 'row',
        gap: 8,
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    currentSessionEditButton: {
        backgroundColor: colours.blue,
        borderRadius: 10,
        paddingVertical: 2,
        paddingHorizontal: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    currentSessionEditText: {
        color: colours.black,
        fontSize: 12,
        fontFamily: 'Lato-Regular',
    },
    currentSessionTitle: {
        fontSize: 19,
        fontFamily: 'Lato-Regular',
        color: colours.black,
    },
    currentSessionText: {
        fontSize: 14,
        fontFamily: 'Lato-Regular',
        color: colours.secondarytext,
    },

    button: {
        backgroundColor: colours.primary,
        padding: 8,
        borderRadius: 11,
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        
        shadowOffset: {height: 4},
        shadowOpacity: 0.3,
        shadowRadius: 3,
        shadowColor: colours.shadowDarkColour,
        elevation: 8,
    },
    buttonText: {
        color: 'white',
        fontSize: 18,
        fontFamily: 'Lato',
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
      },
      modalContent: {
        width: '90%',
        maxWidth: 300,
        borderWidth: 1.5,
        borderColor: colours.backgroundColour,
        backgroundColor: 'white',
        marginHorizontal: 20,
        paddingVertical: 20,
        paddingHorizontal: 18,
        borderRadius: 19,
        gap: 15,
        display: 'flex',
      },
      modalText: {
        fontSize: 18,
        marginBottom: 20,
        fontFamily: 'Lato',
      },
      divider: {
        height: 1.5,
        backgroundColor: '#ccc',
        width: '70%',
      },
      inputContainer: {
        gap: 9,
        display: 'flex',
      },
      inputLabel: {
          fontSize: 16,
          color: colours.subtitletext,
      },
      textInput: {
          backgroundColor: 'rgba(0, 0, 0, 0.04);',
          borderWidth: 1.5,
          borderColor: 'rgba(0, 0, 0, 0.05);',
          borderRadius: 4,
          paddingHorizontal: 10,
          paddingVertical: 8,
          fontSize: 15,
          fontFamily: 'Lato',
          textAlignVertical: 'top'
      },
      createButton: {
          backgroundColor: colours.primary,
          padding: 8,
          gap: 1,
          borderRadius: 10,
          alignItems: 'center',
          justifyContent: 'center',
      },
      createButtonText: {
          color: 'white',
          fontSize: 18,
          fontFamily: 'Lato',
      },
      cancelButton: {
          alignItems: 'center',
          justifyContent: 'center',
          backgroundColor: 'rgba(0, 0, 0, 0.04)',
          width: 79,
          padding: 8,
          borderRadius: 10,
      },
      cancelButtonText: {
          color: '#7B6B5C',
          fontSize: 16,
          fontFamily: 'Lato',
      },

      duringSessionFrame: {
        width: '100%',
        padding: 12,
        paddingVertical: 22,
        backgroundColor: colours.blue,
        shadowOffset: {height: 4},
        shadowOpacity: 0.4,
        elevation: 8,
        shadowRadius: 10,
        borderRadius: 12,
        flexDirection: 'column',
        justifyContent: 'space-evenly',
        alignItems: 'center',
        gap: 10,
    },
    duringSessionUpperSection: {
        width: '90%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    duringSessionTextContainer: {
        flex: 1,
        flexDirection: 'column', 
        justifyContent: 'center', 
        alignItems: 'flex-start', 
    },
    duringSessionTitleText: {
        color: colours.backgroundColour, 
        fontSize: 26, 
        fontFamily: 'Lato-Bold',
        fontWeight: '800',
    },
    duringSessionTimeLeftContainer: {
        backgroundColor: colours.primary,
        width: "90%",
        paddingVertical: 10,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        display: 'flex',
        flexDirection: 'row',
        ...Platform.select({
            ios: {
                shadowColor: colours.shadowDarkColour,
                shadowOffset: { height: 3 },
                shadowOpacity: 0.5,
                shadowRadius: 10,
            },
            android: {
                elevation: 15,
            },
        }),
    },
    duringSessionTimeLeftText: {
        color: colours.white,
        fontSize: 65,
        fontFamily: 'Lato-Bold',
        fontWeight: '800',
        textShadowOffset: {width: 0, height: 3.7},
        textShadowRadius: 6,
        textShadowColor: 'rgba(0, 0, 0, 0.25)',
    },
    duringSessionTimeLeftMinutesText: {
        color: colours.white,
        fontSize: 26,
        fontFamily: 'Lato-Bold',
        fontWeight: '800',
        textShadowOffset: {width: 0, height: 3.7},
        textShadowRadius: 6,
        textShadowColor: 'rgba(0, 0, 0, 0.25)',
    },
    duringSessionCancelSessionButton: {
        backgroundColor: colours.incorrectRed,
        paddingVertical: 7,
        paddingHorizontal: 22,
        borderRadius: 11,
        alignItems: 'center',
        justifyContent: 'center',
        shadowOffset: {height: 4},
        shadowOpacity: 0.3,
        shadowRadius: 3,
        shadowColor: colours.shadowDarkColour,
        elevation: 8,
    },
    duringSessionCancelSessionText: {
        color: colours.white,
        fontSize: 18,
        fontFamily: 'Lato',
    },

    sessionMainButtonText: {
        color: colours.white,
        fontSize: 34,
        fontFamily: 'Lato-Bold',
        fontWeight: '800',
        textShadowOffset: {width: 0, height: 3.7},
        textShadowRadius: 6,
        textShadowColor: 'rgba(0, 0, 0, 0.25)',
    },
    rewardAnimationContainer: {
        position: 'absolute',
        width: '160%',
        height: '55%',
        alignItems: 'center',
        justifyContent: 'center',
    }
}
export default styles;