import colours from "../../config/colours";
const styles = {
    container: {
        flex: 1,
        backgroundColor: colours.backgroundColour,
        alignItems: 'center',
        paddingHorizontal: 25,
        gap: 18,
    },
    currentSessionView: {
        backgroundColor: colours.backgroundAccent,
        borderRadius: 11,
        padding: 9,
        width: '100%',
        alignItems: 'flex-start',
        justifyContent: 'center',
        display: 'flex',
        flexDirection: 'column',
        gap: 5,
        shadowOffset: {width: -2, height: 2},
        shadowOpacity: 0.3,
        shadowRadius: 3,
        shadowColor: colours.shadowDarkColour,
        elevation: 8,
    },
    currentSessionTextContainer: {
        display: 'flex',
        width: '100%',
        flexDirection: 'row',
        gap: 8,
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    currentSessionEditButton: {
        backgroundColor: colours.blue,
        borderRadius: 10,
        paddingVertical: 2,
        paddingHorizontal: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    currentSessionEditText: {
        color: colours.black,
        fontSize: 12,
        fontFamily: 'Lato-Regular',
    },
    currentSessionTitle: {
        fontSize: 19,
        fontFamily: 'Lato-Regular',
        color: colours.black,
    },
    currentSessionText: {
        fontSize: 14,
        fontFamily: 'Lato-Regular',
        color: colours.secondarytext,
    },

    button: {
        backgroundColor: colours.primary,
        padding: 8,
        borderRadius: 11,
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        
        shadowOffset: {width: -2, height: 4},
        shadowOpacity: 0.3,
        shadowRadius: 3,
        shadowColor: colours.shadowDarkColour,
        elevation: 8,
    },
    buttonText: {
        color: 'white',
        fontSize: 18,
        fontFamily: 'Lato',
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
      },
      modalContent: {
        width: '90%',
        maxWidth: 300,
        borderWidth: 1.5,
        borderColor: colours.backgroundColour,
        backgroundColor: 'white',
        marginHorizontal: 20,
        paddingVertical: 20,
        paddingHorizontal: 18,
        borderRadius: 19,
        gap: 15,
        display: 'flex',
      },
      modalText: {
        fontSize: 18,
        marginBottom: 20,
        fontFamily: 'Lato',
      },
      divider: {
        height: 1.5,
        backgroundColor: '#ccc',
        width: '70%',
      },
      inputContainer: {
        gap: 9,
        display: 'flex',
      },
      inputLabel: {
          fontSize: 16,
          color: colours.subtitletext,
      },
      textInput: {
          backgroundColor: 'rgba(0, 0, 0, 0.04);',
          borderWidth: 1.5,
          borderColor: 'rgba(0, 0, 0, 0.05);',
          borderRadius: 4,
          paddingHorizontal: 10,
          paddingVertical: 8,
          fontSize: 15,
          fontFamily: 'Lato',
          textAlignVertical: 'top'
      },
      createButton: {
          backgroundColor: colours.primary,
          padding: 8,
          gap: 1,
          borderRadius: 10,
          alignItems: 'center',
          justifyContent: 'center',
      },
      createButtonText: {
          color: 'white',
          fontSize: 18,
          fontFamily: 'Lato',
      },
      cancelButton: {
          alignItems: 'center',
          justifyContent: 'center',
          backgroundColor: 'rgba(0, 0, 0, 0.04)',
          width: 79,
          padding: 8,
          borderRadius: 10,
      },
      cancelButtonText: {
          color: '#7B6B5C',
          fontSize: 16,
          fontFamily: 'Lato',
      },
}
export default styles;