import colours from "../../config/colours";
const styles = {
    container: {
        flex: 1,
        backgroundColor: colours.backgroundColour,
        alignItems: 'center',
        paddingHorizontal: 25,
        gap: 18,
    },
    currentSessionView: {
        backgroundColor: colours.backgroundAccent,
        borderRadius: 11,
        padding: 9,
        width: '100%',
        alignItems: 'flex-start',
        justifyContent: 'center',
        display: 'flex',
        flexDirection: 'column',
        gap: 5,

        borderWidth: 1.5,
        borderColor: `rgba(0, 0, 0, 0.005)`,

        shadowColor: 'rgba(0, 0, 0, 0.1)',
        shadowOpacity: 0.25,
        elevation: 6,
        shadowRadius: 3 ,
        shadowOffset : { width: 1, height: 6},
    },
    currentSessionTextContainer: {
        display: 'flex',
        width: '100%',
        flexDirection: 'row',
        gap: 8,
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    currentSessionEditButton: {
        backgroundColor: colours.primaryAccent,
        borderRadius: 10,
        paddingVertical: 2,
        paddingHorizontal: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    currentSessionEditText: {
        color: colours.black,
                fontFamily: 'Lato',
fontSize: 12,
    },
    currentSessionTitle: {
                fontFamily: 'Lato',
fontSize: 19,
        color: colours.black,
    },
    currentSessionText: {
                fontFamily: 'Lato',
fontSize: 14,
        color: colours.secondarytext,
    },

    button: {
        backgroundColor: colours.primary,
        padding: 8,
        borderRadius: 11,
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        
        shadowColor: 'rgba(0, 0, 0, 0.1)',
        shadowOpacity: 0.25,
        elevation: 6,
        shadowRadius: 3 ,
        shadowOffset : { width: 1, height: 6},

        borderWidth: 1.5,
        borderColor: `rgba(0, 0, 0, 0.005)`,
    },
    buttonText: {
        color: colours.text,
                fontFamily: 'Lato',
fontSize: 18,
        
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
        width: '90%',
        maxWidth: 300,
        borderWidth: 1.5,
        borderColor: colours.backgroundColour,
        backgroundColor: colours.white,
        marginHorizontal: 20,
        paddingVertical: 20,
        paddingHorizontal: 18,
        borderRadius: 19,
        gap: 15,
        display: 'flex',
    },
    modalText: {
                fontFamily: 'Lato',
fontSize: 18,
        marginBottom: 20,
        
        color: colours.subtitletext,
    },
    divider: {
        height: 1.5,
        backgroundColor: '#ccc',
        width: '70%',
    },
    inputContainer: {
        gap: 9,
        display: 'flex',
    },
    inputLabel: {
        fontFamily: 'Lato',
        fontSize: 16,
        color: colours.subtitletext,
    },
    textInput: {
        backgroundColor: 'rgba(0, 0, 0, 0.04);',
        borderWidth: 1.5,
        borderColor: 'rgba(0, 0, 0, 0.05);',
        borderRadius: 4,
        paddingHorizontal: 10,
        paddingVertical: 8,
        fontFamily: 'Lato',
        fontSize: 15,
        
        textAlignVertical: 'top'
    },
    createButton: {
        backgroundColor: colours.primary,
        padding: 8,
        gap: 1,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    createButtonText: {
        color: colours.text,
        fontFamily: 'Lato',
        fontSize: 18,
        fontWeight: '500',
    },
    cancelButton: {
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.04)',
        width: 79,
        padding: 8,
        borderRadius: 10,
    },
    cancelButtonText: {
        color: '#7B6B5C',
        fontFamily: 'Lato',
        fontSize: 16,
    },

    duringSessionFrame: {
        width: '90%',
        paddingVertical: 10,
        backgroundColor: colours.backgroundAccent,
        shadowColor: 'rgba(0, 0, 0, 0.1)',
        shadowOpacity: 0.25,
        elevation: 6,
        shadowRadius: 3,
        shadowOffset : { width: 1, height: 6},
        borderRadius: 15,
        flexDirection: 'column',
        justifyContent: 'space-evenly',
        alignItems: 'center',
        gap: 10,
        borderWidth: 1.5,
        borderColor: `rgba(0, 0, 0, 0.05)`,
    },
    duringSessionTextContainer: {
        flex: 1,
        flexDirection: 'column', 
        justifyContent: 'center', 
        alignItems: 'flex-start', 
    },
    duringSessionTitleText: {
        color: colours.primaryAccent, 
        fontFamily: 'Lato',
        fontSize: 26, 
        fontWeight: '700',
        marginTop: 15,
    },
    duringSessionTimeLeftContainer: {
        backgroundColor: colours.backgroundAccent,
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        display: 'flex',
        flexDirection: 'row',
    },
    duringSessionTimeLeftText: {
        color: colours.primary,
        fontFamily: 'Lato',
        fontSize: 110,
        fontWeight: '800',
    },
    duringSessionTimeLeftMinutesText: {
        color: colours.primaryAccent,
        fontFamily: 'Lato',
        fontSize: 26,
        fontWeight: '700',
    },
    duringSessionCancelSessionButton: {
        backgroundColor: colours.incorrectRed,
        padding: 10,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: 'rgba(0, 0, 0, 0.1)',
        shadowOpacity: 0.25,
        elevation: 6,
        shadowRadius: 3 ,
        shadowOffset : { width: 1, height: 6},
        elevation: 8,
    },
    duringSessionCancelSessionText: {
        color: colours.white,
        fontFamily: 'Lato',
        fontSize: 18,
        fontWeight: '500',
    },
    sessionMainButtonText: {
        color: colours.white,
        fontFamily: 'Lato',
        fontSize: 34,
        fontWeight: '800',
    },
    rewardAnimationContainer: {
        position: 'absolute',
        width: '160%',
        height: '55%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    claimFrame: {
        width: '100%',
        paddingVertical: 24,
        backgroundColor: colours.backgroundAccent,
        shadowColor: 'rgba(0, 0, 0, 0.1)',
        shadowOpacity: 0.25,
        elevation: 6,
        shadowRadius: 3 ,
        shadowOffset : { width: 1, height: 6},
        borderRadius: 12,
        flexDirection: 'column',
        justifyContent: 'space-evenly',
        alignItems: 'center',
        gap: 12,
        borderWidth: 1.5,
        borderColor: `rgba(0, 0, 0, 0.05)`,
        marginTop: '100%',
    },
    claimUpperSection: {
        width: '90%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    claimButtonContainer: {
        backgroundColor: colours.primary,
        padding: 20,
        borderRadius: 13,
    },
    claimTitleText: {
        color: colours.secondary, 
                fontFamily: 'Lato',
fontSize: 24,
        alignSelf: 'center', 
        fontWeight: '600',
    },
    claimButtonText: {
        color: colours.white,
                fontFamily: 'Lato',
fontSize: 36,
        fontWeight: '600',
    },
    claimSkipContainer: {
        flex: 1, 
        justifyContent: 'flex-end', 
        marginBottom: 20
    },
    claimButtonGroupContainer: { 
        position: 'absolute',
        width: '100%', 
        height: '100%', 
        alignItems: 'center',
        justifyContent: 'center' 
    },
}
export default styles;