import { StyleSheet } from 'react-native';
import colours from '../../../config/colours.js';

export default StyleSheet.create({
    container: {
        flex: 1,
        paddingHorizontal: 18,
        backgroundColor: colours.backgroundColour,
        alignItems: 'center',
        gap: 20,
    },
    subtitleText: {
        fontFamily: 'Lato',
        fontSize: 20,
        fontWeight: '400',
        color: colours.subtitletext,
        marginBottom: 11,
    },
    revisionOptionsContainer: {
        marginTop: 30,
        marginBottom: 15,
        width: '100%',
        maxWidth: 500,
        display: 'flex',
        alignItems: 'center',
        flexDirection: 'column',
        flex: 1,
        gap: 15,
    },
    revisionOption: {
        width: '100%',
        padding: 11,
        alignItems: 'center',
        borderRadius: 11,
        backgroundColor: colours.backgroundAccent,
        flexDirection: 'row',
        display: 'flex',
        gap: 9,
        borderWidth: 1.5,
        borderColor: `rgba(0, 0, 0, 0.005)`,
        shadowColor: 'rgba(0, 0, 0, 0.1)',
        shadowOpacity: 0.1,
        elevation: 6,
        shadowRadius: 3,
        shadowOffset : { width: 1, height: 6},
    },
    revisionOptionIcon: {
        width: 40,
        height: 40,
    },
    revisionOptionsTextContainer: {
        display: 'flex',
        flex: 1,
        width: '100%',
        flexDirection: 'column',
        justifyContent: 'center',
        gap: 7,
        alignItems: 'flex-start',
    },
    revisionOptionTitle: {
        fontWeight: '400',
        fontFamily: 'Lato',
        fontSize: 19,
        color: colours.black,
    },
    revisionOptionDescription: {
        fontFamily: 'Lato',
        fontSize: 12,
        color: colours.secondarytext,
    },
    image: {
        width: 200,
        height: 200,
        marginBottom: 20,
    },
    title: {
        fontFamily: 'Lato',
        fontSize: 24,
        fontWeight: '500',
        marginBottom: 10,
        textAlign: 'center',
        color: colours.subtitletext,
    },
    description: {
        fontFamily: 'Lato',
        fontSize: 16,
        marginBottom: 20,
        textAlign: 'center',
        color: colours.secondarytext,
    },
    button: {
        backgroundColor: colours.primary,
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 8,
    },
    buttonText: {
        color: colours.white,
        fontFamily: 'Lato',
        fontSize: 18,
        fontWeight: '600',
    },
    restartContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
        backgroundColor: colours.backgroundColour,
    },
}) 