import { StyleSheet } from 'react-native';
import colours from '../../config/colours.js';

export default StyleSheet.create({
    subtitleText: {
        fontFamily: 'Lato',
        fontSize: 21,
        fontWeight: '400',
        color: colours.subtitletext,
        marginBottom: 11,
        alignSelf: 'center',
    },
    scrollDataItemButton: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 11,
        backgroundColor: colours.backgroundAccent,
        borderWidth: 1.5,
        borderColor: `rgba(0, 0, 0, 0.005)`,
        marginVertical: 5.5,
        paddingVertical: 4,
        paddingLeft: 16,
        paddingRight: 4,
        gap: 12,
        alignSelf: 'stretch',
        shadowColor: 'rgba(0, 0, 0, 0.1)',
        shadowOpacity: 0.25,
        elevation: 6,
        shadowRadius: 3,
        shadowOffset : { width: 1, height: 6},
        minHeight: 75,
        maxWidth: 500,
    },
    scrollDataButtonContainer: {
        flex: 1,
        paddingLeft: 2.8,
        marginVertical: 5.5,
        maxHeight: 70,
        flexDirection: 'row',
        alignItems: 'center',
    },
    scrollDataButton: {
        borderRadius: 13,
        width: 70,
        marginLeft: 0.5,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 5,
        height: '95%',
    },
    scrollDataTopicButton: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 13,
        backgroundColor: colours.backgroundAccent,
        borderWidth: 1.5,
        borderColor: `rgba(0, 0, 0, 0.02)`,
        marginVertical: 5.5,
        paddingVertical: 9,
        paddingLeft: 16,
        paddingRight: 4,
        gap: 8,
        alignSelf: 'stretch',
        shadowColor: 'rgba(0, 0, 0, 0.1)',
        shadowOpacity: 0.15,
        elevation: 6,
        shadowRadius: 2,
        shadowOffset : { width: 1, height: 6},
        flex: 1,
    },

    scrollDataIconContainer: {
        marginBottom: 5,
    },
    scrollDataButtonText: {
        paddingRight: 50,
        fontWeight: '400',
        fontFamily: 'Lato',
        fontSize: 21,
        color: colours.black,
        overflow: 'hidden',
    },
    scrollDataModalButton: {
        borderWidth: 0.75,
        borderColor: colours.secondarytext,
        borderRadius: 10,
        width: 70,
        height: 32,
        margin: 2,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 5,
    },

    scrollDataContainer: {
        flex: 1,
        paddingTop: 10,
        paddingHorizontal: 0,
        backgroundColor: colours.backgroundColour,
    },
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    buttonText: {
        color: colours.text,
        fontFamily: 'Lato',
        fontSize: 18,
    },
    button: {
        backgroundColor: colours.primary,
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 5,
        marginTop: 20,
    },
    modalContainer: {
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        position: 'absolute',
        width: '100%',
        height: '100%',
    },
    modalSubContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        height: '70%',
    },
    modalContent: {
        width: '90%',
        height: 'auto',
        maxWidth: 300,
        borderWidth: 1.5,
        borderColor: colours.backgroundColour,
        backgroundColor: colours.white,
        marginHorizontal: 20,
        paddingVertical: 20,
        paddingHorizontal: 18,
        borderRadius: 19,
        gap: 15,
        display: 'flex',
    },
    modalTitle: {
        fontFamily: 'Lato',
        fontSize: 20,
        marginBottom: 10,
        fontWeight: '600',
        color: colours.subtitletext,
    },
    inputContainer: {
        gap: 9,
        display: 'flex',
    },
    inputLabel: {
        fontFamily: 'Lato',
        fontSize: 16,
        color: colours.subtitletext,
    },
    textInput: {
        backgroundColor: 'rgba(0, 0, 0, 0.04);',
        borderWidth: 1.5,
        borderColor: 'rgba(0, 0, 0, 0.05);',
        borderRadius: 4,
        paddingHorizontal: 10,
        paddingVertical: 8,
        fontFamily: 'Lato',
        fontSize: 15,
        textAlignVertical: 'top'
    },
    createButton: {
        backgroundColor: colours.primary,
        padding: 8,
        gap: 1,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        
        shadowColor: 'rgba(0, 0, 0, 0.1)',
        shadowOpacity: 0.25,
        elevation: 6,
        shadowRadius: 3,
        shadowOffset : { width: 1, height: 6},
    },
    createButtonText: {
        color: colours.text,
        fontFamily: 'Lato',
        fontSize: 18,
        fontWeight: '500',
    },
    cancelButton: {
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.04)',
        width: 79,
        padding: 8,
        borderRadius: 10,
    },
    cancelButtonText: {
        color: '#7B6B5C',
        fontFamily: 'Lato',
        fontSize: 16,
    },
    generateButton: {
        backgroundColor: colours.primary,
        padding: 8,
        borderRadius: 10,
        alignItems: 'center',
        flexDirection: 'row',
    },
    generateButtonText: {
        color: colours.text,
        fontFamily: 'Lato',
        fontSize: 18,
    },
    generateButtonSubText: {
        color: colours.backgroundAccent,
        fontFamily: 'Lato',
        fontSize: 12,
    },
    button: {
        width: '100%',
        marginHorizontal: 5,
        height: 50,
        gap: 10,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 13,
        borderWidth: 2,
        borderColor: `rgba(0, 0, 0, 0.03)`,
        flexDirection: 'row',

        shadowColor: 'rgba(0, 0, 0, 0.1)',
        shadowOpacity: 0.25,
        elevation: 6,
        shadowRadius: 3,
        shadowOffset : { width: 1, height: 6},
    },
    buttonText: {
        fontFamily: 'Lato',
        fontSize: 21,
        fontWeight: '600',
    },
    divider: {
        height: 1.5,
        backgroundColor: '#ccc',
        width: '100%',
        marginVertical: 8,
    },
})