// 32 quotes
export default [
    "“The secret of getting ahead is getting started.” – Mark Twain",
    "“Believe you can and you're halfway there.” – Theodore Roosevelt",
    "“Success is not final, failure is not fatal: It is the courage to continue that counts.” – Winston Churchill",
    "“The only way to do great work is to love what you do.” – Steve Jobs",
    "“The future depends on what you do today.” – Mahatma Gandhi",
    "“Don't watch the clock; do what it does. Keep going.” – Sam Levenson",
    "“The harder you work for something, the greater you'll feel when you achieve it.” – Unknown",
    "“Your time is limited, don't waste it living someone else's life.” – Steve Jobs",
    "“The only limit to our realization of tomorrow will be our doubts of today.” – Franklin D. Roosevelt",
    "“The journey of a thousand miles begins with one step.” – Lao Tzu",
    "“I find that the harder I work, the more luck I seem to have.” – Thomas Jefferson",
    "“Success is not in what you have, but who you are.” – Bo Bennett",
    "“The expert in anything was once a beginner.” – Helen Hayes",
    "“Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.” – Roy T. Bennett",
    "“You don't have to be great to start, but you have to start to be great.” – Zig Ziglar",
    "“The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.” – Joel Brown",
    "“The only person you should try to be better than is the person you were yesterday.” – Unknown",
    "“It does not matter how slowly you go as long as you do not stop.” – Confucius",
    "“You don't have to see the whole staircase, just take the first step.” – Martin Luther King Jr.",
    "“The future belongs to those who believe in the beauty of their dreams.” – Eleanor Roosevelt",
    "“Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.” – Christian D. Larson",
    "“Don’t be afraid to give up the good to go for the great.” – John D. Rockefeller",
    "“Success is not about the destination, but the journey.” – Unknown",
    "“The mind is everything. What you think, you become.” – Buddha",
    "“In the middle of every difficulty lies opportunity.” – Albert Einstein",
    "“Dream big and dare to fail.” – Norman Vaughan",
    "“Do what you can, with what you have, where you are.” – Theodore Roosevelt",
    "“Believe in the power of your dreams.” – Unknown",
    "“Don't let yesterday take up too much of today.” – Will Rogers",
    "“Challenges are what make life interesting, and overcoming them is what makes life meaningful.” – Joshua J. Marine",
    "“The best time to plant a tree was 20 years ago. The second best time is now.” – Chinese Proverb",
    "“The only limit to our realization of tomorrow will be our doubts of today.” – Franklin D. Roosevelt",
    "“One day, all your hard work will pay off.”",
    "“The earlier you start working on something, the earlier you will see results.”",
    "“Life is short. Live it. Fear is natural. Face it. Memory is powerful. Use it.”",
    "“Do what is right, not what is easy.”",
    "“We generate fears while we do nothing. We overcome these fears by taking action.”",
    "“If we wait until we’re ready, we’ll be waiting for the rest of our lives.”",
    "“It’s never too late to be what you might have been.”",
    "“You don’t have to be great to start. But you have to start to be great.”",
    "“Every morning you have two choices: continue to sleep with your dreams, or wake up and chase them.”",
    "“Nobody can go back and start a new beginning, but anyone can start today and make a new ending.” — MARIA ROBINSON",
    "“Many of life’s failures are people who did not realise how close they were to success when they gave up.” — THOMAS EDISON",
    "“Don’t wish it were easier. Wish you were better.”",
    "“A river cuts through rock not because of its power but because of its persistence.”",
    "“To change your life, you must first change your day.”",
    "“Success is not final, failure is not fatal; it is the courage to continue that counts.” — WINSTON CHURCHILL",
    "“There’s no traffic after the extra mile.”",
    "“Don’t stop until you’re proud.”",
    "“Work as hard as you can and then be happy in the knowledge you couldn’t have done any more.”",
    "“You may see me struggle but you will never see me quit.”",
    "“Work hard in silence. Let success make the noise.”",
    "“If you can believe it, your mind can achieve it.”",
    "“If your dreams don’t scare you, they aren’t big enough.” — MUHAMMAD ALI",
    "“The distance between dreams and reality is called action.”",
    "“The thing about motivated people chasing their dream is they look crazy to lazy people.” — ALBERT EINSTEIN",
    "“The goal is to die with memories not dreams.”",
    "“If you can imagine it, you can achieve it. If you can dream it, you can become it.” — WILLIAM ARTHUR WARD",
    "“So many of our dreams at first seem impossible, then they seem improbable, and then, when we summon the will, they soon become inevitable.” — CHRISTOPHER REEVE",
    "“If you have self-esteem, you give yourself the audacity to dream big.”",
    "“Never let small minds convince you that your dreams are too big.”",
    "“The people who are crazy enough to believe they can change the world are the ones who do.” — STEVE JOBS",
    "“Productivity is about looking forward. Looking back too much, or trying to be too much of a perfectionist, can destroy that productivity. So keep going. Keep creating. Keep building.”",
    "“A system is only as effective as your level of commitment to it.”",
    "“Doing things properly in the first place is the best way to be more productive later. You simply have less to do.”",
    "“What we truly need to do is often what we most feel like avoiding.”",
    "“Productivity boils down to two steps: identify the essential, then eliminate the rest.”",
    "“Infinite striving to be the best is Man’s duty; it is its own reward. Everything else is in God’s hands.” — MAHATMA GANDHI",
    "“The goal is not simply to get more done, but also to have less to do.”",
    "“You were born to win. But to be a winner, you must plan to win, prepare to win and expect to win.” — ZIG ZIGLA",
    "“Hard work beats talent when talent doesn’t work hard.”",
    "“Focus on being productive instead of busy.”",
    "“All the water in the sea can’t sink a ship unless it gets inside the ship. Similarly, all the negativity in the world can’t get you down unless you allow it inside you.”",
    "“Worrying is silly. It’s like wandering around with an umbrella waiting for it to rain.”",
    "“Impossible is not a fact. It is an opinion.”",
    "“When it rains, look for rainbows. When it’s dark, look for stars.”",
    "“Be the spark everyone needs to brighten up their day.”",
    "“Life is a grindstone. Whether it grinds you down or polishes you up is for you alone to decide.” — CAVETT ROBERT",
    "“Worrying doesn’t take away tomorrow’s troubles. It takes away today’s peace.”",
    "“Too many people overvalue what they are not and undervalue what they are.”",
    "“Someone else is happy with less than what you have.”",
    "“Happiness is not a station you arrive at, but a manner of travelling.”",
    "“You don’t learn to walk by following rules. You learn by doing, and by falling over.” — RICHARD BRANSON",
    "“More people would learn from their mistakes if they weren’t so busy denying them.” — HAROLD J. SMITH",
    "“A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.” — GEORGE BERNARD SHAW",
    "“Learn from yesterday. Live for today. Hope for tomorrow.” — ALBERT EINSTEIN",
    "“I gave myself permission to make mistakes. I wouldn’t ever give myself permission not to try.” — STEVE PAVLINA",
    "“You either get bitter or you get better.”",
    "“The lessons you learn on your journey towards your destination will always be more valuable than the destination itself.”",
    "“When life puts you in tough situations, don’t say ‘why me,’ say ‘try me’!”",
    "“Mistakes are the portals of discovery.” — JAMES JOYCE",
    "“Insanity is doing the same thing over and over again, but expecting different results.” — ALBERT EINSTEIN",
    "“Fear is most commonly an acronym for False Evidence Appearing Real.”",
    "“Great things never come from comfort zones.”",
    "“Don’t let the fear of failure be greater than the excitement of success.”",
    "“To overcome fear, you must go through it, not around it.”",
    "“FEAR – Forget Everything And Run… or… Face Everything And Rise. It’s your choice.”",
    "“In the end, we only regret the chances we didn’t take.”",
    "“Remembering you are going to die is the best way to avoid the trap of thinking you have something to lose.” - STEVE JOBS",
    "“It’s not because things are difficult that we do not dare. It is because we do not dare that they are difficult.” - SENECA",
    "“Fear is the brain’s way of saying that there is something important for you to overcome.”",
    "“Most of the things you worry about never even happen.”",
    "“How can you move onto the next chapter of your life if you keep rereading the last one?”",
    "“Fail often so you can succeed sooner.”",
    "“Behind every successful person, there are a lot of unsuccessful years.”",
    "“Life is 10% what happens to me and 90% how I react to it.”",
    "“Doubt kills more dreams that failure ever will.”",
    "“Nothing you do now can change the past. But I promise you, everything you do now will determine your future.”",
    "“Inhale the future. Exhale the past.”",
    "“Failure defeats losers. Failure inspires winners.”",
    "“Be strong because things will get better. It may be stormy now, but it never rains forever.”",
    "“Our greatest glory is not in never failing, but in rising every time we fail.” - CONFUCIUS",
    "“Today a reader. Tomorrow a leader.”",
    "“Discovery consists of seeing what everybody has seen and thinking what nobody has thought.” - ALBERT SZENT-GYORGYI",
    "“When you talk, you are only repeating what you already know. But if you listen, you may learn something new.” - DALAI LAMA",
];