import { StyleSheet } from 'react-native';
import colours from '../../../../config/colours';

export default StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        backgroundColor: colours.backgroundColour,
    },
    subtitleText: {
        fontFamily: 'Lato',
        fontSize: 20,
        fontWeight: '400',
        color: colours.subtitletext,
        marginBottom: 10,
    },
    progressBar: {
        height: 11,
        flexDirection: "row",
        width: '80%',
        backgroundColor: colours.backgroundAccent,
        borderWidth: 0.8,
        borderColor: `rgba(0, 0, 0, 0.1)`,
        borderRadius: 5
    },
    progressBarFiller: {
        height: 9,
        backgroundColor: colours.primary,
        borderRadius: 5,
    },
    questioningContainer: {
        marginTop: 10,
        padding: 11,
        width: '100%',
        flex: 1,
        justifyContent: 'space-evenly',
        alignItems: 'center',
    },
    question: {
        width: '100%',
        display: 'flex',
        justifyContent: 'center',
        fontFamily: 'Lato',
        fontSize: 19,
        textAlign: 'left',
        color: colours.black,
    },

    // Multiple Choice Styles
    optionContainer: {
        width: '100%',
        display: 'flex',
        paddingVertical: 11,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 16,
        alignSelf: 'flex-end',
    },
    optionButton: {
        display: 'flex',
        width: '100%',
        borderRadius: 8,
        minHeight: 50,
        justifyContent: 'center',
        backgroundColor: colours.backgroundAccent,
    },
    optionText: {
        width: '100%',
        padding: 8,
        flexDirection: 'column',
        alignSelf: 'stretch',
        color: colours.subtitletext,
        fontFamily: 'Lato',
        fontSize: 17,
    },

    // Written Styles
    answerContainer: {
        width: '100%',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 16,
        alignSelf: 'flex-end',
    },
    textInput: {
        width: '100%',
        minHeight: 50,
        paddingHorizontal: 10,
        fontFamily: 'Lato',
        fontSize: 17,
        
        textAlignVertical: 'top',
    },
    underline: {
        width: '100%',
        height: 4,
        backgroundColor: colours.primary,
        marginTop: 10,
        marginHorizontal: 30,
        borderRadius: 10,
    },
    submitButton: {
        backgroundColor: colours.primary,
        padding: 8,
        gap: 1,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },

    // Modal Styles
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
        width: '85%',
        maxWidth: 400,
        borderWidth: 1.5,
        borderColor: colours.backgroundColour,
        backgroundColor: colours.white,
        marginHorizontal: 15,
        paddingVertical: 20,
        paddingHorizontal: 18,
        borderRadius: 19,
        gap: 15,
        flexDirection: 'column',
    },
    modalTitle: {
                fontFamily: 'Lato',
fontSize: 20,
        marginBottom: 10,
        fontWeight: '600',
        color: colours.subtitletext,
    },
    modalTextContainer: {
        gap: 8,
        marginVertical: 5,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    modalTextLabel: {
                fontFamily: 'Lato',
fontSize: 16,
        color: colours.secondarytext,
        
    },
    modalText: {
        textAlign: 'right',
                fontFamily: 'Lato',
fontSize: 19,
        
        color: colours.subtitletext,
        flex: 1,
    },
    modalButton: {
        backgroundColor: colours.primary,
        padding: 8,
        gap: 1,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalButtonText: {
        color: colours.text,
        fontFamily: 'Lato',
        fontSize: 18,
    },
    changeGotQCorrectButton: {
        backgroundColor: colours.backgroundColour,
        borderWidth: 1.5,
        borderColor: 'rgba(0, 0, 0, 0.01)',
        padding: 8,
        gap: 1,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    changeGotQCorrectButtonText: {
        color: colours.black,
        fontFamily: 'Lato',
        fontSize: 18,
    },

    // Round Review Styles
    roundReviewContainer: {
        flex: 1,
        paddingVerticle: 5,
        backgroundColor: colours.backgroundColour,
    },
    roundReviewDataContainer: {
        paddingHorizontal: 12,
        width: '100%',
        gap: 15,
        paddingVertical: 25,
    },
    roundReviewCorrectContainer: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        alignItems: 'center',
        gap: 12,
    },
    roundReviewCorrectTextContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    roundReviewCorrectText: {
        fontFamily: 'Lato',
        fontSize: 18,
        fontWeight: '400',
        color: colours.subtitletext,
    },
    inspirationalQuoteContainer: {
        padding: 8,
        width: '100%',
        gap: 2,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 9,
        borderWidth: 2,
        borderColor: `rgba(0, 0, 0, 0.03)`,
        backgroundColor: colours.primaryAccent,
    },
    inspirationalQuoteLabel: {
        width: '100%',
        color: colours.gray,
        fontFamily: 'Lato',
        fontSize: 16,
        
    },
    inspirationalQuoteText: {
        width: '100%',
        color: colours.white,
        fontFamily: 'Lato',
        fontSize: 18,
    },
    nextRoundButton: {
        width: '100%',
        height: 50,
        gap: 10,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 9,
        borderWidth: 2,
        borderColor: `rgba(0, 0, 0, 0.03)`,
        flexDirection: 'row',
        backgroundColor: colours.primary,
    },
    nextRoundButtonText: {
        color: colours.white,
        fontFamily: 'Lato',
        fontSize: 21,
         fontWeight: '600',
    },

    // Flashcard Styles
    flashcardFront: {
        width: '82%',
        backgroundColor: colours.backgroundAccent,
        borderWidth: 1.5,
        borderColor: `rgba(0, 0, 0, 0.05)`,
        borderRadius: 18,
        padding: 20,
        backfaceVisibility: "hidden",
        position: "absolute",
        alignItems: "flex-start",
        shadowColor: 'rgba(0, 0, 0, 0.1)',
        shadowOpacity: 0.25,
        elevation: 6,
        shadowRadius: 3,
        shadowOffset : { width: 1, height: 6},
     },
     flashcardBack: {
        width: '82%',
        backgroundColor: colours.backgroundAccent,
        borderWidth: 1.5,
        borderColor: `rgba(0, 0, 0, 0.05)`,
        borderRadius: 18,
        padding: 20,
        backfaceVisibility: "hidden",
        alignItems: "flex-start",
        shadowColor: 'rgba(0, 0, 0, 0.1)',
        shadowOpacity: 0.25,
        elevation: 6,
        shadowRadius: 3,
        shadowOffset : { width: 1, height: 6},
     },
     flashcardTitleText: {
        fontFamily: 'Lato',
        fontSize: 20,
        fontWeight: '500',
        color: colours.black,
        alignSelf: 'center',
     },
    gotQCorrectImage: {
        width: 75,
        height: 75,
        alignSelf: 'center',
    },
})