import { StyleSheet } from 'react-native';
import colours from '../../../config/colours.js';

export default StyleSheet.create({
    container: {
        flex: 1,
        paddingVerticle: 5,
        paddingHorizontal: 8,
        backgroundColor: colours.backgroundColour,
        alignItems: 'center',
    },
    subtitleText: {
        fontSize: 20,
        fontFamily: 'Lato-Bold', fontWeight: '600',
        color: colours.subtitletext,
        marginBottom: 23,
    },
    button: {
        width: '100%',
        marginHorizontal: 5,
        height: 50,
        gap: 10,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 13,
        borderWidth: 2,
        borderColor: `rgba(0, 0, 0, 0.03)`,
        flexDirection: 'row',

        shadowColor: colours.shadowColour,
        elevation: 5,
        shadowOffset: {height: 4},
        shadowOpacity: 0.2,
        shadowRadius: 5,
    },
    buttonText: {
        fontSize: 21,
        fontFamily: 'Lato-Bold', fontWeight: '600',
    },
    divider: {
        height: 1.5,
        backgroundColor: '#ccc',
        width: '100%',
        marginVertical: 8,
    },
    cardsContainer: {
        marginTop: 20,
        marginBottom: 11,
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
    },
    card: {
        width: '100%',
        minHeight: 90,
        padding: 5,
        alignItems: 'flex-start',
        justifyContent: 'center',
        borderRadius: 13,
        backgroundColor: colours.backgroundAccent,
        flexDirection: 'row',
        display: 'flex',
        gap: 2,
        borderWidth: 1,
        borderColor: `rgba(0, 0, 0, 0.02)`,
        marginBottom: 8,
    },
    cardSubContainer: {
        flex: 1,
        alignItems: 'flex-start',
        justifyContent: 'center',
        flexDirection: 'column',
        display: 'flex',
        gap: 5,
    },
    cardTextContainer: {    
        paddingHorizontal: 4,
        paddingVertical: 5,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 4,
        alignItems: 'center',
    },
    cardTitleText: {
        width: 95,
        fontFamily: 'Lato',
        fontSize: 19,
        color: colours.secondarytext,
        overflow: 'hidden',
    },
    cardText: {
        fontFamily: 'Lato',
        fontSize: 19,
        color: colours.subtitletext,
        overflow: 'hidden',
        display: 'flex',
        flex: 1,
        textAlignVertical: 'top',
    },
    swipeContainer: {
        flex: 1,
        paddingLeft: 2.8,
        marginBottom: 8,
        flexDirection: 'row',
        alignItems: 'center',
    },
    swipeButton: {
        borderRadius: 13,
        width: 70,
        marginLeft: 0.5,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 5,
        height: '100%',
    },
    swipeIconContainer: {
        marginBottom: 5,
    },
    swipeButtonText: {
        fontFamily: 'Lato',
        color: 'white',
        fontSize: 15,
    },
}) 