import { StyleSheet } from 'react-native';
import colours from '../../config/colours.js';

export default StyleSheet.create({
    scrollDataItemButton: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 11,
        backgroundColor: colours.backgroundAccent,
        borderWidth: 1.5,
        borderColor: `rgba(0, 0, 0, 0.005)`,
        marginVertical: 5,
        paddingVertical: 4,
        paddingLeft: 16,
        paddingRight: 4,
        height: 75,
        gap: 12,
        alignSelf: 'stretch',
        shadowOffset: {height: 2},
        shadowOpacity: 0.03,
        shadowRadius: 3,
        shadowColor: colours.shadowColour,
        elevation: 5,
    },
    scrollDataButtonContainer: {
        flex: 1,
        paddingLeft: 2.8,
        marginVertical: 5.5,
        maxHeight: 75,
        flexDirection: 'row',
        alignItems: 'center',
    },
    scrollDataButton: {
        borderRadius: 11,
        width: 75,
        marginLeft: 0.5,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 5,
        height: '95%',
    },
    scrollDataIconContainer: {
        marginBottom: 5,
    },
    scrollDataButtonText: {
        fontFamily: 'Lato',
        color: 'white',
        fontSize: 15,
    },
    scrollDataModalButton: {
        borderWidth: 0.75,
        borderColor: colours.secondarytext,
        borderRadius: 10,
        width: 70,
        height: 32,
        margin: 2,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 5,
    },

    scrollDataContainer: {
        flex: 1,
        paddingTop: 10,
        paddingHorizontal: 0,
        backgroundColor: colours.backgroundColour,
    },
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    buttonText: {
        color: 'white',
        fontSize: 18,
    },
    button: {
        backgroundColor: colours.primary,
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 5,
        marginTop: 20,
    },
    modalContainer: {
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        position: 'absolute',
        width: '100%',
        height: '100%',
    },
    modalSubContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        height: '70%',
    },
    modalContent: {
        width: '90%',
        height: 'auto',
        maxWidth: 300,
        borderWidth: 1.5,
        borderColor: colours.backgroundColour,
        backgroundColor: 'white',
        marginHorizontal: 20,
        paddingVertical: 20,
        paddingHorizontal: 18,
        borderRadius: 19,
        gap: 15,
        display: 'flex',
    },
    modalTitle: {
        fontSize: 20,
        marginBottom: 10,
        fontFamily: 'Lato-Bold', fontWeight: '600',
        fontWeight: '600',
        color: colours.subtitletext,
    },
    inputContainer: {
        gap: 9,
        display: 'flex',
    },
    inputLabel: {
        fontSize: 16,
        color: colours.subtitletext,
    },
    textInput: {
        backgroundColor: 'rgba(0, 0, 0, 0.04);',
        borderWidth: 1.5,
        borderColor: 'rgba(0, 0, 0, 0.05);',
        borderRadius: 4,
        paddingHorizontal: 10,
        paddingVertical: 8,
        fontSize: 15,
        fontFamily: 'Lato',
        textAlignVertical: 'top'
    },
    createButton: {
        backgroundColor: colours.primary,
        padding: 8,
        gap: 1,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        
        shadowOffset: {height: 4},
        shadowOpacity: 0.3,
        shadowRadius: 5,
        shadowColor: colours.shadowColour,
        elevation: 5,
    },
    createButtonText: {
        color: 'white',
        fontSize: 18,
        fontFamily: 'Lato',
    },
    cancelButton: {
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.04)',
        width: 79,
        padding: 8,
        borderRadius: 10,
    },
    cancelButtonText: {
        color: '#7B6B5C',
        fontSize: 16,
        fontFamily: 'Lato',
    },
    divider: {
        height: 1,
        backgroundColor: '#ccc',
    },
    generateButton: {
        backgroundColor: colours.purple,
        padding: 8,
        borderRadius: 10,
        alignItems: 'center',
        flexDirection: 'row',
    },
    generateButtonText: {
        color: 'white',
        fontSize: 18,
        fontFamily: 'Lato',
    },
    generateButtonSubText: {
        color: colours.backgroundAccent,
        fontSize: 12,
        fontFamily: 'Lato',
    },
    importButton: {
        backgroundColor: colours.blue,
        padding: 8,
        borderRadius: 10,
        alignItems: 'center',
        flexDirection: 'row',
    },
    importButtonText: {
        color: colours.white,
        fontSize: 18,
        fontFamily: 'Lato',
    },
    importButtonSubText: {
        color: colours.white,
        fontSize: 12,
        fontFamily: 'Lato',
    },
    
    noSetsFrame: {
        width: '100%',
        height: 170,
        padding: 12,
        backgroundColor: colours.blue,
        shadowOffset: {height: 4},
        shadowOpacity: 0.3,
        shadowColor: colours.shadowColour,
        elevation: 5,
        shadowRadius: 5,
        borderRadius: 12,
        flexDirection: 'column',
        justifyContent: 'space-evenly',
        alignItems: 'center',
        gap: 10,
    },
    noSetsUpperSection: {
        width: '90%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    noSetsTextContainer: {
        flex: 1,
        flexDirection: 'column', 
        justifyContent: 'center', 
        alignItems: 'flex-start', 
        gap: 10, 
    },
    noSetsTitleText: {
        color: colours.backgroundColour, 
        fontSize: 26, 
        fontFamily: 'Lato-Bold', fontWeight: '600',
        fontWeight: '600',
    },
    noSetsSubText: {
        color: '#F5EEE9', 
        fontSize: 13, 
        fontFamily: 'Lato', 
        fontWeight: '600', 
    },
    noSetsCreateButton: {
        backgroundColor: colours.primary,
        width: "90%",
        paddingVertical: 10,
        gap: 1,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: colours.shadowColour,
        elevation: 5,
        shadowOffset: {height: 4},
        shadowOpacity: 0.05,
        shadowRadius: 2,
        borderRadius: 12,
        display: 'flex',
    },
    dropdown: {
        height: 10,
        paddingHorizontal: 12,
        marginLeft: 'auto',
    },
    dropdownLabel: {
        zIndex: 999,
        fontSize: 17,
        fontFamily: 'Lato',
        color: colours.darkPrimary,
        fontWeight: '500',
    },
    dropdownIcon: {
        zIndex: 999,
        marginLeft: 5,
        marginTop: 2,
    },
})